name: Terraform AWS Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TF_VERSION: "1.5.7"  # Replace with your preferred Terraform version

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"  # Replace with your preferred region

      - name: Terraform Workspace - Create and Select
        run: |
          terraform workspace new production || true
          terraform workspace select production

      - name: Terraform Init
        run: terraform init
      - name: Check if RDS exists
        id: check-rds
        run: |
          # Use a script to check if the RDS instance exists
          # Set an output variable 'rds_exists' based on the check
          if [ check_if_rds_exists ]; then
            echo "RDS exists"
            echo "rds_exists=true" >> $GITHUB_ENV
          else
            echo "RDS does not exist"
            echo "rds_exists=false" >> $GITHUB_ENV
          fi

      - name: Create RDS (conditional)
        if: env.rds_exists != 'true'
        run: terraform apply -auto-approve


     